version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:5.2.2
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    # networks:
    #   - sparing-12-network

  # mosquitto:
  #   image: eclipse-mosquitto:2.0
  #   container_name: mosquitto
  #   ports:
  #     - "1883:1883"
  #   restart: unless-stopped
  #   volumes:
  #   - ./mosquitto/config:/mosquitto/config
  #   - ./mosquitto/data:/mosquitto/data
  #   - ./mosquitto/log:/mosquitto/log

  mqtt-service:
    build: ./mqtt-service
    container_name: mqtt-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - energy-service
    environment:
      - MQTT_BROKER_URL=${MQTT_BROKER_URL}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - DB_SERVICE_URL=${DB_SERVICE_URL}

  # mqtt-dummy:
  #   build: ./mqtt-dummy
  #   container_name: mqtt-dummy
  #   depends_on:
  #     - mosquitto
  #   environment:
  #     - MQTT_BROKER_URL=${MQTT_BROKER_URL}
  #     - MQTT_TOPIC_PREFIX=${MQTT_TOPIC_PREFIX}
  #     - PLC_ID=${PLC_ID}
  #     - PUBLISH_INTERVAL=${PUBLISH_INTERVAL}

  energy-service:
    build: ./energy-service
    container_name: energy-service
    ports:
      - "8001:8001"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}

  # modbus-service:
  #   build: ./modbus-service
  #   container_name: modbus-service
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - energy-service
  #   environment:
  #     - DB_SERVICE_URL=http://energy-service:8001
  #     - POLL_INTERVAL=5

volumes:
  mysql_data:
